namespace: magento

replicaCount: 1

image:
  repository: ghcr.io/vinicius05051993/magento-php
  tag: 2.4.9-php8.3
  pullPolicy: Always

nginx:
  image: nginx:stable

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

  className: nginx

  host: magento.local

mysql:
  host: mysql
  database: magento
  user: magento
  password: magento
  crypt: base64I4vCIg81qX3XkPfO0rzMYsvM0c/nqVomOIPJMEXX6W4=

redis:
  host: redis
  port: 6379

opensearch:
  host: opensearch
  port: 9200

magento:
  edition: community

  version: 2.4.9

  mode: developer

  admin:
    firstname: Admin
    lastname: User
    email: admin@example.com
    user: admin
    password: Admin123!
    backend: painel
    timezone: America/Sao_Paulo
    currency: BRL
    language: pt_BR

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"

  limits:
    cpu: "2"
    memory: "3Gi"

externalMysql:
  ip: 172.18.255.10
  port: 3306