apiVersion: apps/v1
kind: Deployment

metadata:
  name: magento

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: magento

  template:

    metadata:
      labels:
        app: magento

    spec:

      securityContext:
        fsGroup: 33

      initContainers:

        - name: copy-magento-code

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - sh
            - -c
            - |
              cp -a /var/www/html/. /mnt/html/

          volumeMounts:

            - name: magento-code
              mountPath: /mnt/html

        - name: prepare-magento-etc

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - sh
            - -c
            - |
              if [ ! -f /mnt/etc/di.xml ]; then
                echo "Initializing app/etc volume..."
                cp -R /var/www/html/app/etc/* /mnt/etc/
                chown -R 33:33 /mnt/etc
              fi

          volumeMounts:

            - name: magento-etc
              mountPath: /mnt/etc

        - name: magento-install

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - /bin/bash
            - -c
            - |
              set -e

              cd /var/www/html

              echo "Waiting MySQL..."

              until mysqladmin ping \
                --protocol=TCP \
                --ssl=0 \
                -h "$MYSQL_HOST" \
                -u root \
                -p"$MYSQL_ROOT_PASSWORD" \
                --silent; do

                echo "MySQL not ready..."
                sleep 3

              done

              echo "MySQL OK"

              echo "Waiting OpenSearch..."

              until curl -s "http://$OPENSEARCH_HOST:$OPENSEARCH_PORT" > /dev/null; do

                echo "OpenSearch not ready..."
                sleep 3

              done

              echo "OpenSearch OK"

              echo "Waiting Redis..."

              until redis-cli -h "$REDIS_HOST" ping > /dev/null; do

                echo "Redis not ready..."
                sleep 3

              done

              echo "Redis OK"

              if [ ! -s app/etc/env.php ] || ! grep -q "'crypt'" app/etc/env.php; then

                echo "Magento not installed"

                php -d memory_limit=-1 bin/magento setup:install \
                  --base-url="$MAGENTO_BASE_URL" \
                  --db-host="$MYSQL_HOST" \
                  --db-name="$MYSQL_DATABASE" \
                  --db-user="$MYSQL_USER" \
                  --db-password="$MYSQL_PASSWORD" \
                  --key="$MAGENTO_CRYPT_KEY" \
                  --admin-firstname="$MAGENTO_ADMIN_FIRSTNAME" \
                  --admin-lastname="$MAGENTO_ADMIN_LASTNAME" \
                  --admin-email="$MAGENTO_ADMIN_EMAIL" \
                  --admin-user="$MAGENTO_ADMIN_USER" \
                  --admin-password="$MAGENTO_ADMIN_PASSWORD" \
                  --language="$MAGENTO_LANGUAGE" \
                  --currency="$MAGENTO_CURRENCY" \
                  --timezone="$MAGENTO_TIMEZONE" \
                  --use-rewrites=1 \
                  --backend-frontname="$MAGENTO_BACKEND_FRONTNAME" \
                  --search-engine=opensearch \
                  --opensearch-host="$OPENSEARCH_HOST" \
                  --opensearch-port="$OPENSEARCH_PORT" \
                  --cache-backend=redis \
                  --cache-backend-redis-server="$REDIS_HOST" \
                  --cache-backend-redis-db=0 \
                  --page-cache=redis \
                  --page-cache-redis-server="$REDIS_HOST" \
                  --page-cache-redis-db=1 \
                  --session-save=redis \
                  --session-save-redis-host="$REDIS_HOST" \
                  --session-save-redis-db=2

                echo "Disabling unused modules..."

                php bin/magento module:disable Magento_Marketplace
                php bin/magento module:disable Magento_Ups
                php bin/magento module:disable Magento_Usps
                php bin/magento module:disable Magento_AdminAdobeImsTwoFactorAuth
                php bin/magento module:disable Magento_TwoFactorAuth

                sleep 30

                php -d memory_limit=-1 \
                  bin/magento setup:static-content:deploy -f pt_BR en_US

                php -d memory_limit=-1 \
                  bin/magento setup:di:compile

                php bin/magento indexer:reindex

                php bin/magento cache:flush

                echo "Magento installed"

              else

                echo "Magento already installed"

              fi

              chown -R 33:33 app/etc pub/media var generated
              chmod -R ug+rwX app/etc pub/media var generated
                
              if [ -d /var/www/.config/composer ]; then
                  chown -R 33:33 /var/www/.config/composer
                  chmod -R u+rwX,go+rX /var/www/.config/composer
              fi

          envFrom:

            - configMapRef:
                name: magento-config

            - secretRef:
                name: magento-secret

          volumeMounts:

            - name: magento-code
              mountPath: /var/www/html

            - name: magento-etc
              mountPath: /var/www/html/app/etc

            - name: magento-media
              mountPath: /var/www/html/pub/media

            - name: magento-static
              mountPath: /var/www/html/pub/static

            - name: magento-generated
              mountPath: /var/www/html/generated

      containers:

        - name: php

          securityContext:
            runAsUser: 33
            runAsGroup: 33

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          resources:
{{- toYaml .Values.resources | nindent 12 }}

          ports:
            - containerPort: 9000

          envFrom:

            - configMapRef:
                name: magento-config

            - secretRef:
                name: magento-secret

          readinessProbe:
            tcpSocket:
              port: 9000

            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            tcpSocket:
              port: 9000

            initialDelaySeconds: 20
            periodSeconds: 10

          volumeMounts:

            - name: magento-code
              mountPath: /var/www/html

            - name: magento-etc
              mountPath: /var/www/html/app/etc

            - name: magento-media
              mountPath: /var/www/html/pub/media

            - name: magento-static
              mountPath: /var/www/html/pub/static

            - name: magento-generated
              mountPath: /var/www/html/generated

            - name: php-config
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini

        - name: nginx

          image: {{ .Values.nginx.image | quote }}

          ports:
            - containerPort: 80

          volumeMounts:

            - name: magento-code
              mountPath: /var/www/html

            - name: magento-etc
              mountPath: /var/www/html/app/etc

            - name: magento-media
              mountPath: /var/www/html/pub/media

            - name: magento-static
              mountPath: /var/www/html/pub/static

            - name: magento-generated
              mountPath: /var/www/html/generated

            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

      volumes:

        - name: magento-code

          emptyDir: {}

        - name: magento-etc

          emptyDir: {}

        - name: magento-media

          persistentVolumeClaim:
            claimName: magento-media-pvc

        - name: magento-static

          emptyDir: {}

        - name: magento-generated

          emptyDir: {}

        - name: nginx-config

          configMap:
            name: magento-nginx

        - name: php-config

          configMap:
            name: magento-php-config