apiVersion: apps/v1
kind: Deployment

metadata:
  name: magento

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: magento

  template:

    metadata:
      labels:
        app: magento

    spec:

      securityContext:
        fsGroup: 33

      initContainers:

        - name: copy-magento-code

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - sh
            - -c
            - |
              cp -a /var/www/html/. /mnt/html/

          volumeMounts:

            - name: magento-code
              mountPath: /mnt/html

        - name: wait-magento-install

          image: busybox

          command:
            - sh
            - -c
            - |
              until [ -s /mnt/etc/env.php ]; do
                echo "Waiting Magento installation..."
                sleep 5
              done

          volumeMounts:

            - name: magento-etc
              mountPath: /mnt/etc

      containers:

        - name: php

          securityContext:
            runAsUser: 33
            runAsGroup: 33

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          resources:
{{- toYaml .Values.resources | nindent 12 }}

          ports:
            - containerPort: 9000

          envFrom:

            - configMapRef:
                name: magento-config

            - secretRef:
                name: magento-secret

          readinessProbe:
            tcpSocket:
              port: 9000

            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            tcpSocket:
              port: 9000

            initialDelaySeconds: 20
            periodSeconds: 10

          volumeMounts:

            - name: magento-code
              mountPath: /var/www/html

            - name: magento-etc
              mountPath: /var/www/html/app/etc

            - name: magento-media
              mountPath: /var/www/html/pub/media

            - name: magento-static
              mountPath: /var/www/html/pub/static

            - name: magento-generated
              mountPath: /var/www/html/generated

            - name: php-config
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini

        - name: nginx

          image: {{ .Values.nginx.image | quote }}

          ports:
            - containerPort: 80

          volumeMounts:

            - name: magento-code
              mountPath: /var/www/html

            - name: magento-etc
              mountPath: /var/www/html/app/etc

            - name: magento-media
              mountPath: /var/www/html/pub/media

            - name: magento-static
              mountPath: /var/www/html/pub/static

            - name: magento-generated
              mountPath: /var/www/html/generated

            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

      volumes:

        - name: magento-code

          emptyDir: {}

        - name: magento-etc

          persistentVolumeClaim:
            claimName: magento-etc

        - name: magento-media

          persistentVolumeClaim:
            claimName: magento-media

        - name: magento-static

          persistentVolumeClaim:
            claimName: magento-static

        - name: magento-generated

          persistentVolumeClaim:
            claimName: magento-generated

        - name: nginx-config

          configMap:
            name: magento-nginx

        - name: php-config

          configMap:
            name: magento-php-config