apiVersion: batch/v1
kind: Job

metadata:
  name: magento-install

spec:
  backoffLimit: 1

  template:

    metadata:
      labels:
        app: magento-install

    spec:

      restartPolicy: Never

      securityContext:
        fsGroup: 33

      initContainers:

        - name: copy-magento-source

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - sh
            - -c
            - |
              if [ ! -f /mnt/app/bin/magento ]; then
                echo "Copying Magento source..."
                cp -R /var/www/html/. /mnt/app/
              else
                echo "Magento source already exists"
              fi

          volumeMounts:

            - name: magento-src
              mountPath: /mnt/app

      containers:

        - name: magento-install

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - /usr/local/bin/job-install-magento.sh

          envFrom:

            - configMapRef:
                name: magento-config

            - secretRef:
                name: magento-secret

          volumeMounts:

            - name: magento-src
              mountPath: /var/www/html

      volumes:

        - name: magento-src

          persistentVolumeClaim:
            claimName: magento-src