apiVersion: batch/v1
kind: Job

metadata:
  name: magento-install

spec:
  backoffLimit: 1

  template:

    metadata:
      labels:
        app: magento-install

    spec:

      restartPolicy: Never

      securityContext:
        fsGroup: 33

      initContainers:

        - name: prepare-magento-etc

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - sh
            - -c
            - |
              if [ ! -f /mnt/etc/di.xml ]; then
                echo "Initializing app/etc volume..."
                cp -R /var/www/html/app/etc/* /mnt/etc/
                chown -R 33:33 /mnt/etc
              fi

          volumeMounts:

            - name: magento-etc
              mountPath: /mnt/etc

      containers:

        - name: magento-install

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - /usr/local/bin/job-install-magento.sh

          envFrom:

            - configMapRef:
                name: magento-config

            - secretRef:
                name: magento-secret

          volumeMounts:

            - name: magento-etc
              mountPath: /var/www/html/app/etc

            - name: magento-media
              mountPath: /var/www/html/pub/media

            - name: magento-static
              mountPath: /var/www/html/pub/static

            - name: magento-generated
              mountPath: /var/www/html/generated

      volumes:

        - name: magento-etc

          persistentVolumeClaim:
            claimName: magento-etc

        - name: magento-media

          persistentVolumeClaim:
            claimName: magento-media

        - name: magento-static

          persistentVolumeClaim:
            claimName: magento-static

        - name: magento-generated

          persistentVolumeClaim:
            claimName: magento-generated