apiVersion: v1
kind: Secret

metadata:
  name: magento-secret

type: Opaque

stringData:
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}

  MAGENTO_ADMIN_PASSWORD: {{ .Values.magento.admin.password | quote }}

  MAGENTO_PUBLIC_KEY: {{ .Values.magento.repo.publicKey | quote }}

  MAGENTO_PRIVATE_KEY: {{ .Values.magento.repo.privateKey | quote }}