apiVersion: v1
kind: Secret

metadata:
  name: magento-secret

type: Opaque

stringData:
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}

  MAGENTO_ADMIN_PASSWORD: {{ .Values.magento.admin.password | quote }}

  MAGENTO_CRYPT_KEY: {{ .Values.mysql.crypt | quote }}