apiVersion: v1
kind: Secret

metadata:
  name: mysql-secret
  namespace: magento

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_DATABASE: magento
  MYSQL_USER: magento
  MYSQL_PASSWORD: magento123