apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: mysql
  namespace: magento

spec:
  serviceName: mysql

  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql

          image: mysql:8.0

          ports:
            - containerPort: 3306

          envFrom:
            - secretRef:
                name: mysql-secret

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

            - name: mysql-config
              mountPath: /etc/mysql/conf.d/custom.cnf
              subPath: custom.cnf

          readinessProbe:
            tcpSocket:
              port: 3306

            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 3306

            initialDelaySeconds: 30
            periodSeconds: 15

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"

            limits:
              memory: "1Gi"
              cpu: "1000m"

      volumes:
        - name: mysql-config

          configMap:
            name: mysql-config

  volumeClaimTemplates:
    - metadata:
        name: mysql-storage

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 20Gi