apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: magento-media-pvc
  namespace: magento

spec:

  storageClassName: standard

  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 20Gi

  volumeName: magento-media-pv